apiVersion: v2
name: hysteria
description:  Hysteria is a powerful, lightning fast and censorship resistant proxy. 
type: application
version: 0.1.0
appVersion: v2.6.5
maintainers:
  - name: allanger
    email: allanger@zohomail.com
    url: https://badhouseplants.net
dependencies:
  - name: helm-library
    version: 0.2.6
    repository: oci://ghcr.io/allanger/allangers-helm-library
annotations:
  allowed_workload_kinds: "Deployment"
sources:
  - https://github.com/apernet/hysteria
keywords:
  - hysteria
  - vpn
  - proxy
home: https://v2.hysteria.network/
