apiVersion: v2
name: gotosocial
description: Fast, fun, small ActivityPub server.
type: application
version: 0.1.0
appVersion: 0.20.1
maintainers:
  - name: allanger
    email: allanger@zohomail.com
    url: https://badhouseplants.net
dependencies:
  - name: helm-library
    version: 0.2.5
    repository: oci://ghcr.io/allanger/allangers-helm-library
annotations:
  allowed_workload_kinds: "Deployment"
sources:
  - https://codeberg.org/superseriousbusiness/gotosocial
keywords:
  - gotosocial
home: https://gotosocial.org/
