apiVersion: v2
name: navidrome
description: Modern Music Server and Streamer compatible with Subsonic/Airsonic
type: application
version: 1.4.0
appVersion: 0.60.3
maintainers:
  - name: allanger
    email: allanger@zohomail.com
    url: https://badhouseplants.net
dependencies:
  - name: helm-library
    version: 0.2.5
    repository: oci://ghcr.io/allanger/allangers-helm-library
annotations:
  allowed_workload_kinds: "Deployment"
sources:
  - https://github.com/navidrome/navidrome
keywords:
  - navidrome
  - music
home: https://www.navidrome.org/
